echo "Algorytmy wyd. VI"
echo "Kompilacja w trakcie..."
c++ -o 255 255.cpp
c++ -o a a.cpp
c++ -o ananas ananas.cpp
c++ -o binary-i binary-i.cpp
c++ -o binary-s binary-s.cpp
c++ -o binarys_stl binarys_stl.cpp
c++ -o binary_i binary_i.cpp
c++ -o binary_s binary_s.cpp
c++ -o bit-operations bit-operations.cpp
c++ -o bity bity.cpp
c++ -o bit_operations bit_operations.cpp
c++ -o bm bm.cpp
c++ -o breadth breadth.cpp
c++ -o bubble bubble.cpp
c++ -o complex complex.cpp
c++ -o depthf depthf.cpp
c++ -o dobor dobor.cpp
c++ -o dyn dyn.cpp
c++ -o dziedzic dziedzic.cpp
c++ -o erastot erastot.cpp
c++ -o eratost eratost.cpp
c++ -o eukl eukl.cpp
c++ -o fib-dyn fib-dyn.cpp
c++ -o fib fib.cpp
c++ -o floyd floyd.cpp
c++ -o floyd2 floyd2.cpp
c++ -o gauss gauss.cpp
c++ -o greedy greedy.cpp
c++ -o hanoi hanoi.cpp
c++ -o hanoi2 hanoi2.cpp
c++ -o hanoi_it hanoi_it.cpp
c++ -o hash hash.cpp
c++ -o heap heap.cpp
c++ -o heapsort heapsort.cpp
c++ -o horner horner.cpp
c++ -o insert insert.cpp
c++ -o interpol interpol.cpp
c++ -o kmp kmp.cpp
c++ -o kolejka-int kolejka-int.cpp
c++ -o kolejka-string kolejka-string.cpp
c++ -o kompoz kompoz.cpp
c++ -o lcs lcs.cpp
c++ -o linear linear.cpp
c++ -o list-tab list-tab.cpp
c++ -o lista lista.cpp
c++ -o lista2 lista2.cpp
c++ -o list_tab list_tab.cpp
c++ -o McCarthy McCarthy.cpp
c++ -o merge merge.cpp
c++ -o merge2 merge2.cpp
c++ -o min-max min-max.cpp
c++ -o n n.cpp
c++ -o newton newton.cpp
c++ -o nwd nwd.cpp
c++ -o oblicz oblicz.cpp
c++ -o odwr-tab odwr-tab.cpp
c++ -o odwrot2 odwrot2.cpp
c++ -o odwrotna odwrotna.cpp
c++ -o palindro palindro.cpp
c++ -o pliki pliki.cpp
c++ -o pochodna pochodna.cpp
c++ -o post2-dod post2-dod.cpp
c++ -o post2 post2.cpp
c++ -o post_2 post_2.cpp
c++ -o post_2_dod post_2_dod.cpp
c++ -o pot pot.cpp
c++ -o qsort-cormen qsort-cormen.cpp
c++ -o qsort qsort.cpp
c++ -o qsort2 qsort2.cpp
c++ -o ref ref.cpp
c++ -o reksearch reksearch.cpp
c++ -o reszta reszta.cpp
c++ -o rev_tab rev_tab.cpp
c++ -o rk rk.cpp
c++ -o scalaj scalaj.cpp
c++ -o sciezka sciezka.cpp
c++ -o sdw sdw.cpp
c++ -o shaker shaker.cpp
c++ -o silinia_ite silinia_ite.cpp
c++ -o silnia-ite silnia-ite.cpp
c++ -o silnia silnia.cpp
c++ -o silnia2 silnia2.cpp
c++ -o simpson simpson.cpp
c++ -o sterta sterta.cpp
c++ -o stl-array -std=c++11 stl-array.cpp
c++ -o stl-forwardlist -std=c++11 stl-forwardlist.cpp 
c++ -o stl-lista stl-lista.cpp
c++ -o stl-map stl-map.cpp
c++ -o stl-queue stl-queue.cpp
c++ -o stl-set stl-set.cpp
c++ -o stl-stos stl-stos.cpp
c++ -o stl-vector stl-vector.cpp
c++ -o stos stos.cpp
c++ -o stosfloa stosfloa.cpp
c++ -o string string.cpp
c++ -o struct struct.cpp
c++ -o systemsort systemsort.cpp
c++ -o szukaj-txt szukaj-txt.cpp
c++ -o szukaj szukaj.cpp
c++ -o tablice tablice.cpp
c++ -o tictac tictac.cpp
c++ -o tictactoe tictactoe.cpp
c++ -o uss uss.cpp
c++ -o warshall warshall.cpp
c++ -o wartf wartf.cpp
c++ -o wielom wielom.cpp
c++ -o wielom2 wielom2.cpp
c++ -o wsk-fun wsk-fun.cpp
c++ -o wsk-fun2 wsk-fun2.cpp
c++ -o wsk_fun wsk_fun.cpp
c++ -o wsk_fun2 wsk_fun2.cpp
c++ -o wyrazen wyrazen.cpp
c++ -o xor xor.cpp
c++ -o zbior zbior.cpp
c++ -o znaki znaki.cpp
echo "KONIEC!"

